server:
  port: 8081
  servlet:
    context-path: /prueba-backend
spring:
  application:
    name: prueba-backend
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: "jdbc:oracle:thin:@prueba-oracle:1521:xe"
    username: "PRUEBA"
    password: "1234"
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
